-- ============================================================
-- TERRA — Supabase schema (bảng, phân quyền RLS, kho file, trigger)
-- Chạy toàn bộ file này trong Supabase Dashboard > SQL Editor, sau đó chạy supabase/seed.sql.
-- Chạy lại nhiều lần được (idempotent): dùng "if not exists" / "create or replace" / xoá-tạo policy.
--
-- Mô hình quyền:
--   anon / người dùng thường : ĐỌC nội dung đã xuất bản; GỬI form liên hệ + hồ sơ ứng tuyển (không đọc lại được)
--   admin (có trong bảng admin_users) : toàn quyền nội dung + xem/xử lý liên hệ, hồ sơ, CV
-- Thêm admin: tạo user ở Authentication > Users, rồi
--   insert into public.admin_users (user_id, email) select id, email from auth.users where email = 'admin@terra.vn';
-- ============================================================

-- ---------- Tiện ích chung ----------

create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================
-- 1. Quản trị viên
-- ============================================================
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

-- security definer: đọc admin_users mà không bị chính RLS của bảng chặn (tránh đệ quy policy)
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

alter table public.admin_users enable row level security;
drop policy if exists "Admin users: read self or admin" on public.admin_users;
create policy "Admin users: read self or admin" on public.admin_users
  for select using (user_id = auth.uid() or public.is_admin());
-- Thêm / xoá admin chỉ qua SQL Editor (service role), không có policy ghi.

-- ============================================================
-- 2. Dự án
-- ============================================================
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('Căn hộ', 'Biệt thự', 'Đất nền', 'Shophouse')),
  location text not null,
  status text not null check (status in ('Đang mở bán', 'Sắp mở bán', 'Đã bàn giao')),
  price numeric not null check (price >= 0), -- tỷ VNĐ
  interest_count integer not null default 0, -- lượt quan tâm (sort "Quan tâm nhiều nhất"), tự tăng khi có yêu cầu tư vấn
  popularity integer not null default 0 check (popularity between 0 and 100), -- sort "Phổ biến"
  building_type text not null default 'apartment' check (building_type in ('apartment', 'villa', 'land', 'shophouse')),
  description text,
  created_at timestamptz not null default now() -- sort "Mới nhất"
);
-- Cột bổ sung (thêm được vào bảng projects tạo từ schema cũ)
alter table public.projects add column if not exists overview jsonb; -- { developer, scale[], landArea, buildingDensity, ownership, amenities, handover }
alter table public.projects add column if not exists cover_image_url text; -- trống → ảnh minh hoạ theo loại hình
alter table public.projects add column if not exists is_published boolean not null default true;
alter table public.projects add column if not exists sort_order integer not null default 0;
alter table public.projects add column if not exists updated_at timestamptz not null default now();

drop trigger if exists projects_updated_at on public.projects;
create trigger projects_updated_at before update on public.projects
  for each row execute function public.set_updated_at();

-- Ảnh "Không gian sống" của dự án (mục ảnh thực tế + tham quan 3D)
create table if not exists public.project_gallery (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects (id) on delete cascade,
  room text not null, -- tên phòng, vd "Phòng khách" (dùng để ghép với mặt bằng trong tham quan 3D)
  description text not null default '',
  image_url text not null,
  depth_url text, -- bản đồ độ sâu (tuỳ chọn) — có thì tham quan 3D có chiều sâu
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists project_gallery_project_idx on public.project_gallery (project_id, sort_order);

-- ============================================================
-- 3. Mặt bằng
--    Mỗi bộ mặt bằng gắn với MỘT loại hình (mặc định cho mọi dự án loại đó)
--    hoặc MỘT dự án cụ thể (ghi đè bộ mặc định).
-- ============================================================
create table if not exists public.floor_plan_sets (
  id bigint generated by default as identity primary key,
  building_type text check (building_type in ('apartment', 'villa', 'land', 'shophouse')),
  project_id bigint references public.projects (id) on delete cascade,
  title text not null,
  intro text not null default '',
  updated_at timestamptz not null default now(),
  constraint floor_plan_sets_one_scope check ((building_type is null) <> (project_id is null))
);
create unique index if not exists floor_plan_sets_building_uq on public.floor_plan_sets (building_type) where project_id is null;
create unique index if not exists floor_plan_sets_project_uq on public.floor_plan_sets (project_id) where project_id is not null;

drop trigger if exists floor_plan_sets_updated_at on public.floor_plan_sets;
create trigger floor_plan_sets_updated_at before update on public.floor_plan_sets
  for each row execute function public.set_updated_at();

create table if not exists public.floor_plans (
  id bigint generated by default as identity primary key,
  set_id bigint not null references public.floor_plan_sets (id) on delete cascade,
  slug text not null, -- mã tab dùng trong web, vd "t1", "b2"
  name text not null, -- tên tab, vd "Tầng 1", "2 phòng ngủ"
  code text not null, -- mã căn / tầng, vd "T1"
  area numeric not null check (area > 0), -- m²
  bedrooms integer check (bedrooms >= 0),
  bathrooms integer check (bathrooms >= 0),
  note text not null default '',
  width numeric not null check (width > 0), -- m
  depth numeric not null check (depth > 0), -- m
  rooms jsonb not null default '[]' check (jsonb_typeof(rooms) = 'array'), -- [{ label, kind, x, y, w, h }] (mét)
  sort_order integer not null default 0,
  unique (set_id, slug)
);
create index if not exists floor_plans_set_idx on public.floor_plans (set_id, sort_order);

-- ============================================================
-- 4. Tin tức
-- ============================================================
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('du-an', 'cong-ty', 'thien-nguyen')),
  title text not null,
  content text[] not null default '{}', -- mỗi phần tử là một đoạn văn
  image_url text, -- trống → ảnh minh hoạ mặc định
  published_at date not null default current_date,
  is_featured boolean not null default false, -- nhãn "Mới"
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists news_published_idx on public.news (published_at desc);

drop trigger if exists news_updated_at on public.news;
create trigger news_updated_at before update on public.news
  for each row execute function public.set_updated_at();

-- ============================================================
-- 5. Tuyển dụng
-- ============================================================
create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  employment_type text not null default 'Toàn thời gian',
  summary text not null default '',
  icon text not null default 'building' check (icon in ('building', 'megaphone', 'engineer', 'support', 'legal', 'finance')),
  is_open boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists jobs_updated_at on public.jobs;
create trigger jobs_updated_at before update on public.jobs
  for each row execute function public.set_updated_at();

-- ============================================================
-- 6. Yêu cầu tư vấn (form Liên hệ)
-- ============================================================
create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  email text not null,
  project_interest text, -- tên dự án khách quan tâm
  topic text not null,
  message text,
  created_at timestamptz not null default now()
);
alter table public.contact_submissions add column if not exists status text not null default 'new';
alter table public.contact_submissions add column if not exists admin_note text;
alter table public.contact_submissions add column if not exists handled_at timestamptz;
alter table public.contact_submissions add column if not exists updated_at timestamptz not null default now();

do $$ begin
  alter table public.contact_submissions add constraint contact_status_chk check (status in ('new', 'in_progress', 'done', 'spam'));
exception when duplicate_object then null; end $$;
do $$ begin
  -- chặn dữ liệu rác / quá dài gửi thẳng từ trình duyệt
  alter table public.contact_submissions add constraint contact_input_chk check (
    char_length(full_name) between 2 and 120
    and phone ~ '^[0-9+ ]{9,15}$'
    and email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' and char_length(email) <= 200
    and char_length(topic) <= 200
    and coalesce(char_length(project_interest), 0) <= 200
    and coalesce(char_length(message), 0) <= 5000
  ) not valid; -- not valid: không kiểm tra lại dữ liệu cũ, chỉ áp cho dữ liệu mới
exception when duplicate_object then null; end $$;
create index if not exists contact_submissions_status_idx on public.contact_submissions (status, created_at desc);

drop trigger if exists contact_submissions_updated_at on public.contact_submissions;
create trigger contact_submissions_updated_at before update on public.contact_submissions
  for each row execute function public.set_updated_at();

-- Khách gửi yêu cầu tư vấn cho một dự án → tăng lượt quan tâm của dự án đó
create or replace function public.bump_project_interest() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.project_interest is not null then
    update public.projects set interest_count = interest_count + 1 where name = new.project_interest;
  end if;
  return new;
end;
$$;
drop trigger if exists contact_bump_interest on public.contact_submissions;
create trigger contact_bump_interest after insert on public.contact_submissions
  for each row execute function public.bump_project_interest();

-- ============================================================
-- 7. Hồ sơ ứng tuyển
-- ============================================================
create table if not exists public.job_applications (
  id bigint generated by default as identity primary key,
  job_id bigint references public.jobs (id) on delete set null,
  position text not null, -- tên vị trí tại thời điểm nộp (giữ lại kể cả khi tin tuyển dụng bị xoá)
  full_name text not null check (char_length(full_name) between 2 and 120),
  phone text not null check (phone ~ '^[0-9+ ]{9,15}$'),
  email text not null check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' and char_length(email) <= 200),
  cv_url text check (cv_url is null or (cv_url ~* '^https?://' and char_length(cv_url) <= 500)), -- link CV / portfolio
  cv_path text check (cv_path is null or cv_path ~ '^applications/[A-Za-z0-9._-]+$'), -- file CV trong kho "cv"
  message text check (message is null or char_length(message) <= 5000),
  status text not null default 'new' check (status in ('new', 'reviewing', 'interview', 'hired', 'rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists job_applications_status_idx on public.job_applications (status, created_at desc);

drop trigger if exists job_applications_updated_at on public.job_applications;
create trigger job_applications_updated_at before update on public.job_applications
  for each row execute function public.set_updated_at();

-- ============================================================
-- 8. Phân quyền (Row Level Security)
-- ============================================================
alter table public.projects enable row level security;
alter table public.project_gallery enable row level security;
alter table public.floor_plan_sets enable row level security;
alter table public.floor_plans enable row level security;
alter table public.news enable row level security;
alter table public.jobs enable row level security;
alter table public.contact_submissions enable row level security;
alter table public.job_applications enable row level security;

-- Dự án: công khai đọc dự án đã xuất bản
drop policy if exists "Public can read projects" on public.projects;
drop policy if exists "Projects: public read published" on public.projects;
create policy "Projects: public read published" on public.projects
  for select using (is_published or public.is_admin());
drop policy if exists "Projects: admin write" on public.projects;
create policy "Projects: admin write" on public.projects
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Gallery: public read" on public.project_gallery;
create policy "Gallery: public read" on public.project_gallery
  for select using (
    public.is_admin() or exists (select 1 from public.projects p where p.id = project_id and p.is_published)
  );
drop policy if exists "Gallery: admin write" on public.project_gallery;
create policy "Gallery: admin write" on public.project_gallery
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Floor plan sets: public read" on public.floor_plan_sets;
create policy "Floor plan sets: public read" on public.floor_plan_sets for select using (true);
drop policy if exists "Floor plan sets: admin write" on public.floor_plan_sets;
create policy "Floor plan sets: admin write" on public.floor_plan_sets
  for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Floor plans: public read" on public.floor_plans;
create policy "Floor plans: public read" on public.floor_plans for select using (true);
drop policy if exists "Floor plans: admin write" on public.floor_plans;
create policy "Floor plans: admin write" on public.floor_plans
  for all using (public.is_admin()) with check (public.is_admin());

-- Tin tức: chỉ bài đã xuất bản và đã tới ngày đăng
drop policy if exists "News: public read published" on public.news;
create policy "News: public read published" on public.news
  for select using ((is_published and published_at <= current_date) or public.is_admin());
drop policy if exists "News: admin write" on public.news;
create policy "News: admin write" on public.news
  for all using (public.is_admin()) with check (public.is_admin());

-- Tuyển dụng: chỉ vị trí còn mở
drop policy if exists "Jobs: public read open" on public.jobs;
create policy "Jobs: public read open" on public.jobs
  for select using (is_open or public.is_admin());
drop policy if exists "Jobs: admin write" on public.jobs;
create policy "Jobs: admin write" on public.jobs
  for all using (public.is_admin()) with check (public.is_admin());

-- Liên hệ: ai cũng gửi được (không tự đặt trạng thái / ghi chú), chỉ admin đọc & xử lý
drop policy if exists "Public can submit contact form" on public.contact_submissions;
drop policy if exists "Contact: public insert" on public.contact_submissions;
create policy "Contact: public insert" on public.contact_submissions
  for insert with check (status = 'new' and admin_note is null and handled_at is null);
drop policy if exists "Contact: admin read" on public.contact_submissions;
create policy "Contact: admin read" on public.contact_submissions for select using (public.is_admin());
drop policy if exists "Contact: admin update" on public.contact_submissions;
create policy "Contact: admin update" on public.contact_submissions
  for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Contact: admin delete" on public.contact_submissions;
create policy "Contact: admin delete" on public.contact_submissions for delete using (public.is_admin());

-- Hồ sơ ứng tuyển: tương tự liên hệ
drop policy if exists "Applications: public insert" on public.job_applications;
create policy "Applications: public insert" on public.job_applications
  for insert with check (status = 'new' and admin_note is null);
drop policy if exists "Applications: admin read" on public.job_applications;
create policy "Applications: admin read" on public.job_applications for select using (public.is_admin());
drop policy if exists "Applications: admin update" on public.job_applications;
create policy "Applications: admin update" on public.job_applications
  for update using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Applications: admin delete" on public.job_applications;
create policy "Applications: admin delete" on public.job_applications for delete using (public.is_admin());

-- ============================================================
-- 9. Kho file (Supabase Storage)
--   media : ảnh dự án / tin tức — công khai đọc, admin tải lên
--   cv    : file CV ứng viên — riêng tư; khách chỉ tải lên vào thư mục applications/, admin đọc qua link ký tạm
-- ============================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('media', 'media', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif']),
  ('cv', 'cv', false, 5242880, array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Media: public read" on storage.objects;
create policy "Media: public read" on storage.objects for select using (bucket_id = 'media');
drop policy if exists "Media: admin write" on storage.objects;
create policy "Media: admin write" on storage.objects
  for all using (bucket_id = 'media' and public.is_admin()) with check (bucket_id = 'media' and public.is_admin());

drop policy if exists "CV: public upload" on storage.objects;
create policy "CV: public upload" on storage.objects
  for insert with check (bucket_id = 'cv' and (storage.foldername(name))[1] = 'applications');
drop policy if exists "CV: admin read" on storage.objects;
create policy "CV: admin read" on storage.objects for select using (bucket_id = 'cv' and public.is_admin());
drop policy if exists "CV: admin delete" on storage.objects;
create policy "CV: admin delete" on storage.objects for delete using (bucket_id = 'cv' and public.is_admin());
