-- TỰ SINH bởi scripts/seed/generate.mjs — không sửa tay. Chạy sau supabase/schema.sql.
-- Upsert theo id: chạy lại được, không xoá dữ liệu admin đã thêm.
begin;

-- Dự án
insert into public.projects (id, name, type, location, status, price, interest_count, popularity, building_type, description, overview, sort_order, created_at) overriding system value
values
  (1, 'Terra Riverside', 'Căn hộ', 'TP.HCM', 'Đang mở bán', 4.2, 980, 92, 'apartment', null, '{"developer":"Tập đoàn Terra","scale":["Cao 32 tầng, 2 tầng hầm để xe.","Gồm 3 tháp: Sông Xanh, Sông Vàng, Sông Bạc.","Khối đế 4 tầng thương mại & tiện ích nội khu."],"landArea":"15.200 m²","buildingDensity":"35%","ownership":"Sở hữu lâu dài","amenities":"32+ hạng mục tiện ích","handover":"Dự kiến quý IV/2027"}'::jsonb, 0, '2026-10-02T00:00:00+07:00'),
  (2, 'Terra Hills Villa', 'Biệt thự', 'Bình Dương', 'Đang mở bán', 12.5, 640, 75, 'villa', null, '{"developer":"Tập đoàn Terra","scale":["68 căn biệt thự đơn lập & song lập.","Diện tích mỗi căn từ 240 - 400 m².","Thiết kế 1 trệt + 2 lầu, sân vườn riêng."],"landArea":"42.000 m²","buildingDensity":"28%","ownership":"Sở hữu lâu dài","amenities":"20+ hạng mục tiện ích nội khu","handover":"Dự kiến quý III/2026"}'::jsonb, 1, '2026-09-17T00:00:00+07:00'),
  (3, 'Golden Sand Land', 'Đất nền', 'Long An', 'Sắp mở bán', 2.1, 1120, 88, 'land', null, '{"developer":"Tập đoàn Terra","scale":["620 nền đất nền thổ cư đã có sổ.","Diện tích mỗi nền từ 90 - 150 m².","Hạ tầng đường nhựa, điện, cấp thoát nước hoàn thiện 100%."],"landArea":"18,5 ha","buildingDensity":"Tối đa 70% diện tích mỗi nền (theo quy hoạch 1/500)","ownership":"Sở hữu lâu dài, đã có sổ đỏ từng nền","amenities":"12+ hạng mục tiện ích nội khu","handover":"Dự kiến bàn giao đất quý I/2026"}'::jsonb, 2, '2026-10-05T00:00:00+07:00'),
  (4, 'Terra Central Plaza', 'Shophouse', 'TP.HCM', 'Đang mở bán', 8.9, 410, 60, 'shophouse', null, '{"developer":"Tập đoàn Terra","scale":["86 căn shophouse thương mại.","Thiết kế 1 trệt + 4 lầu.","Mặt tiền tiếp giáp trục đường chính khu vực."],"landArea":"9.800 m²","buildingDensity":"55%","ownership":"Sở hữu lâu dài","amenities":"15+ hạng mục tiện ích thương mại","handover":"Đang bàn giao theo tiến độ hợp đồng"}'::jsonb, 3, '2026-08-08T00:00:00+07:00'),
  (5, 'Emerald Riverside', 'Căn hộ', 'Đồng Nai', 'Đã bàn giao', 3.4, 305, 55, 'apartment', null, '{"developer":"Tập đoàn Terra","scale":["Cao 28 tầng, 1 tầng hầm để xe.","Gồm 2 tháp: Emerald A, Emerald B.","Khối đế 3 tầng tiện ích."],"landArea":"11.000 m²","buildingDensity":"38%","ownership":"Sở hữu lâu dài","amenities":"25+ hạng mục tiện ích","handover":"Đã bàn giao — cư dân đang sinh sống"}'::jsonb, 4, '2025-09-02T00:00:00+07:00'),
  (6, 'Terra Coastal Villas', 'Biệt thự', 'Đà Nẵng', 'Sắp mở bán', 15.8, 870, 81, 'villa', null, '{"developer":"Tập đoàn Terra","scale":["45 căn biệt thự nghỉ dưỡng ven biển.","Diện tích mỗi căn từ 300 - 500 m².","Thiết kế 1 trệt + 1 lầu, hồ bơi riêng."],"landArea":"36.000 m²","buildingDensity":"25%","ownership":"Sở hữu lâu dài","amenities":"18+ hạng mục tiện ích nghỉ dưỡng","handover":"Dự kiến quý IV/2026"}'::jsonb, 5, '2026-09-27T00:00:00+07:00'),
  (7, 'Sunrise Garden Land', 'Đất nền', 'Bình Dương', 'Đang mở bán', 1.8, 530, 66, 'land', null, '{"developer":"Tập đoàn Terra","scale":["410 nền đất nền thổ cư.","Diện tích mỗi nền từ 100 - 160 m².","Hạ tầng nội khu đồng bộ, công viên cây xanh trung tâm."],"landArea":"12,4 ha","buildingDensity":"Tối đa 70% diện tích mỗi nền (theo quy hoạch 1/500)","ownership":"Sở hữu lâu dài, đã có sổ đỏ từng nền","amenities":"10+ hạng mục tiện ích nội khu","handover":"Dự kiến bàn giao đất quý III/2026"}'::jsonb, 6, '2026-08-23T00:00:00+07:00'),
  (8, 'Terra Sky Residence', 'Căn hộ', 'Hà Nội', 'Sắp mở bán', 5.6, 750, 79, 'apartment', null, '{"developer":"Tập đoàn Terra","scale":["Cao 35 tầng, 3 tầng hầm để xe.","Gồm 2 tháp: Sky Tower 1, Sky Tower 2.","Khối đế 5 tầng thương mại & tiện ích."],"landArea":"13.600 m²","buildingDensity":"32%","ownership":"Sở hữu lâu dài","amenities":"30+ hạng mục tiện ích","handover":"Dự kiến quý I/2028"}'::jsonb, 7, '2026-09-29T00:00:00+07:00'),
  (9, 'Terra Boulevard Shophouse', 'Shophouse', 'Long An', 'Đã bàn giao', 6.3, 220, 48, 'shophouse', null, '{"developer":"Tập đoàn Terra","scale":["52 căn shophouse mặt tiền đại lộ.","Thiết kế 1 trệt + 3 lầu.","Bố trí liền kề trục đường thương mại chính."],"landArea":"7.200 m²","buildingDensity":"50%","ownership":"Sở hữu lâu dài","amenities":"10+ hạng mục tiện ích","handover":"Đã bàn giao — đang kinh doanh, cho thuê"}'::jsonb, 8, '2025-05-25T00:00:00+07:00'),
  (10, 'Lakeview Residence', 'Căn hộ', 'TP.HCM', 'Đang mở bán', 4.9, 1300, 95, 'apartment', null, '{"developer":"Tập đoàn Terra","scale":["Cao 30 tầng, 2 tầng hầm để xe.","Gồm 3 tháp: Lake View A, B, C.","Khối đế 4 tầng tiện ích, hướng nhìn hồ trung tâm."],"landArea":"16.500 m²","buildingDensity":"36%","ownership":"Sở hữu lâu dài","amenities":"35+ hạng mục tiện ích","handover":"Dự kiến quý II/2027"}'::jsonb, 9, '2026-10-06T00:00:00+07:00'),
  (11, 'Terra Green Valley', 'Biệt thự', 'Đồng Nai', 'Đang mở bán', 9.4, 460, 63, 'villa', null, '{"developer":"Tập đoàn Terra","scale":["58 căn biệt thự song lập trong thung lũng xanh.","Diện tích mỗi căn từ 220 - 380 m².","Thiết kế 1 trệt + 2 lầu, sân vườn bao quanh."],"landArea":"38.000 m²","buildingDensity":"27%","ownership":"Sở hữu lâu dài","amenities":"16+ hạng mục tiện ích","handover":"Dự kiến quý IV/2026"}'::jsonb, 10, '2026-09-04T00:00:00+07:00'),
  (12, 'Metro Junction Land', 'Đất nền', 'Hà Nội', 'Sắp mở bán', 3.9, 690, 72, 'land', null, '{"developer":"Tập đoàn Terra","scale":["350 nền đất nền liền kề gần nhà ga Metro.","Diện tích mỗi nền từ 80 - 120 m².","Hạ tầng kết nối trực tiếp tuyến Metro số 3."],"landArea":"9,6 ha","buildingDensity":"Tối đa 70% diện tích mỗi nền (theo quy hoạch 1/500)","ownership":"Sở hữu lâu dài, đã có sổ đỏ từng nền","amenities":"8+ hạng mục tiện ích nội khu","handover":"Dự kiến bàn giao đất quý II/2026"}'::jsonb, 11, '2026-09-22T00:00:00+07:00')
on conflict (id) do update set
  name = excluded.name,
  type = excluded.type,
  location = excluded.location,
  status = excluded.status,
  price = excluded.price,
  interest_count = excluded.interest_count,
  popularity = excluded.popularity,
  building_type = excluded.building_type,
  description = excluded.description,
  overview = excluded.overview,
  sort_order = excluded.sort_order,
  created_at = excluded.created_at;
select setval(pg_get_serial_sequence('public.projects', 'id'), (select max(id) from public.projects));

-- Tin tức (ảnh để trống → web dùng ảnh mẫu cùng id)
insert into public.news (id, category, title, content, published_at, is_featured, is_published) overriding system value
values
  (1, 'du-an', 'Terra tung ưu đãi "Đặc quyền Priority" cho khách hàng thân thiết', array['Từ ngày 31/07/2026, Terra chính thức triển khai chương trình "Đặc quyền Priority" dành riêng cho nhóm khách hàng thân thiết đã đồng hành cùng dự án từ những giai đoạn đầu tiên.', 'Chương trình bao gồm ưu đãi chiết khấu trực tiếp trên giá bán, hỗ trợ lãi suất 0% trong 24 tháng và quyền ưu tiên chọn căn ở các đợt mở bán tiếp theo.', 'Đại diện chủ đầu tư cho biết đây là lời cảm ơn dành cho những khách hàng đã tin tưởng lựa chọn Terra, đồng thời là bước chuẩn bị cho giai đoạn bàn giao sắp tới.', 'Để đủ điều kiện tham gia, khách hàng cần đáp ứng ít nhất một trong các tiêu chí: đã ký hợp đồng mua bán từ đợt mở bán đầu tiên, sở hữu từ 2 sản phẩm trở lên tại dự án, hoặc được giới thiệu bởi khách hàng cũ đã tham gia chương trình giới thiệu "Refer-a-Friend".', 'Mức chiết khấu áp dụng theo bậc, dao động từ 3% đến 7% tùy vào tổng giá trị giao dịch tích lũy, được cộng dồn trực tiếp vào giá bán niêm yết tại thời điểm ký hợp đồng.', 'Ông Nguyễn Văn A, Giám đốc Kinh doanh Terra, chia sẻ: "Đặc quyền Priority không chỉ là một chính sách bán hàng, mà là cách chúng tôi ghi nhận sự tin tưởng của những khách hàng đã đồng hành cùng dự án ngay từ những ngày đầu tiên, khi mọi thứ còn nằm trên bản vẽ."', 'Khách hàng quan tâm có thể đăng ký tham gia chương trình thông qua ứng dụng chăm sóc khách hàng hoặc trực tiếp tại các văn phòng giao dịch của Terra trên toàn quốc, thời gian xét duyệt dự kiến trong vòng 5 ngày làm việc.', 'Chương trình chính thức áp dụng từ ngày 31/07/2026 và kéo dài đến hết quý I/2027, hoặc cho đến khi đạt đủ số lượng suất ưu đãi giới hạn cho từng đợt.', 'Đây là chương trình tri ân quy mô lớn thứ hai được Terra triển khai kể từ khi mở bán, sau chương trình "Early Bird" hồi năm 2025, và được kỳ vọng sẽ tiếp tục củng cố niềm tin của khách hàng trong giai đoạn nước rút trước ngày bàn giao.']::text[], '2026-07-31', true, true),
  (2, 'du-an', 'Dự án kết nối 2 nhà ga, 2 sân bay quốc tế và 2 thành phố trực thuộc trung ương', array['Terra sở hữu vị trí chiến lược khi nằm giữa hai nhà ga metro và kết nối thuận tiện tới hai sân bay quốc tế, rút ngắn đáng kể thời gian di chuyển tới trung tâm.', 'Hạ tầng giao thông đồng bộ đang được đầu tư mạnh mẽ, mở ra tiềm năng gia tăng giá trị bất động sản trong khu vực ở trung và dài hạn.', 'Đây cũng là yếu tố then chốt giúp cư dân tương lai dễ dàng di chuyển liên vùng, đồng thời gia tăng sức hút với nhà đầu tư đón đầu quy hoạch.', 'Theo quy hoạch giao thông vùng đã được phê duyệt, tuyến metro số 3 dự kiến hoàn thành nhà ga gần Terra vào cuối năm 2027, rút ngắn thời gian di chuyển vào trung tâm xuống còn khoảng 18 phút vào giờ cao điểm.', 'Bên cạnh hệ thống đường sắt đô thị, tuyến cao tốc liên vùng đang thi công song song cũng sẽ kết nối trực tiếp tới hai sân bay quốc tế lớn nhất khu vực, dự kiến thông xe kỹ thuật trong năm 2028.', 'Các chuyên gia bất động sản nhận định, những dự án nằm trên trục hạ tầng trọng điểm như Terra thường ghi nhận mức tăng giá trung bình 15-20% mỗi năm trong giai đoạn hạ tầng hoàn thiện, cao hơn đáng kể so với mặt bằng chung của thị trường.', 'Ngoài lợi thế di chuyển, khu vực xung quanh hai nhà ga cũng đang được quy hoạch thành các cụm tiện ích thương mại - dịch vụ, hứa hẹn hình thành một hành lang đô thị sầm uất trong vòng 5 năm tới.']::text[], '2026-05-25', false, true),
  (3, 'du-an', 'Tiềm năng shophouse Terra nhờ liền kề nhà ga Metro', array['Dãy shophouse khối đế Terra được đánh giá cao nhờ vị trí liền kề trực tiếp nhà ga Metro, đón đầu lượng khách qua lại mỗi ngày.', 'Mô hình kinh doanh đa dạng từ F&B, bán lẻ đến dịch vụ tiện ích được kỳ vọng mang lại dòng tiền khai thác ổn định cho nhà đầu tư.', 'Nhiều thương hiệu lớn đã bày tỏ sự quan tâm và đặt vấn đề thuê mặt bằng ngay từ giai đoạn hoàn thiện phần thô.']::text[], '2026-05-18', false, true),
  (4, 'cong-ty', 'Terra ký kết hợp tác chiến lược cùng 5 đối tác lớn', array['Terra vừa ký kết hợp tác chiến lược với 5 đối tác lớn trong các lĩnh vực xây dựng, vận hành, tài chính và công nghệ.', 'Sự hợp tác này nhằm đảm bảo tiến độ thi công, nâng cao chất lượng bàn giao và mang đến trải nghiệm sống chuẩn quốc tế cho cư dân.', 'Đây là một trong chuỗi hoạt động nằm trong chiến lược phát triển bền vững mà Terra theo đuổi trong giai đoạn 2026-2030.']::text[], '2026-04-30', false, true),
  (5, 'du-an', 'Bàn giao giai đoạn 1: hơn 800 căn hộ chính thức có cư dân sinh sống', array['Hơn 800 căn hộ thuộc giai đoạn 1 của Terra đã chính thức được bàn giao, đánh dấu cột mốc quan trọng của dự án.', 'Nhiều cư dân đã bắt đầu chuyển về sinh sống, tận hưởng hệ thống tiện ích nội khu đồng bộ ngay từ những ngày đầu.', 'Chủ đầu tư cam kết tiếp tục hoàn thiện các giai đoạn tiếp theo đúng tiến độ đã công bố.']::text[], '2026-04-12', false, true),
  (6, 'du-an', 'Tiến độ thi công tháng 3: hoàn thiện phần thô toàn bộ khối đế thương mại', array['Trong tháng 3, toàn bộ phần thô khối đế thương mại của Terra đã được hoàn thiện, đáp ứng đúng tiến độ đề ra.', 'Đội ngũ thi công đang tập trung triển khai hạng mục cơ điện và hoàn thiện mặt ngoài cho các block tiếp theo.', 'Chủ đầu tư khẳng định tiến độ thi công vẫn được kiểm soát chặt chẽ, đảm bảo thời gian bàn giao như cam kết với khách hàng.']::text[], '2026-03-20', false, true),
  (7, 'cong-ty', 'Terra nhận giải thưởng "Dự án đáng sống" tại Lễ trao giải Bất động sản Việt Nam 2026', array['Terra vinh dự nhận giải thưởng "Dự án đáng sống" tại Lễ trao giải Bất động sản Việt Nam 2026, ghi nhận những nỗ lực trong thiết kế và quy hoạch.', 'Giải thưởng được bình chọn dựa trên các tiêu chí về chất lượng sống, tiện ích nội khu và mức độ hài lòng của cư dân thực tế.', 'Đây là sự khích lệ lớn để Terra tiếp tục nâng cao chất lượng ở các dự án tiếp theo.', 'Giải thưởng do Hội đồng gồm hơn 20 chuyên gia độc lập trong lĩnh vực quy hoạch, kiến trúc và quản lý đô thị bình chọn, dựa trên khảo sát thực tế tại hơn 150 dự án trên toàn quốc.', 'Terra được đánh giá cao ở các tiêu chí: mật độ xây dựng hợp lý, tỷ lệ cây xanh trên đầu người, hệ thống tiện ích nội khu đồng bộ và mức độ hài lòng của cư dân đã bàn giao giai đoạn 1.', 'Đại diện Ban tổ chức nhấn mạnh, đây là năm đầu tiên giải thưởng bổ sung tiêu chí khảo sát trực tiếp cư dân đang sinh sống, thay vì chỉ đánh giá trên hồ sơ thiết kế như các năm trước.', 'Terra cho biết sẽ tiếp tục áp dụng các tiêu chuẩn thiết kế đã được vinh danh cho giai đoạn 2 của dự án, đồng thời nghiên cứu bổ sung thêm tiện ích chăm sóc sức khỏe cộng đồng trong quy hoạch tổng thể.']::text[], '2026-06-15', true, true),
  (8, 'cong-ty', 'Terra công bố báo cáo phát triển bền vững thường niên 2025', array['Terra vừa công bố báo cáo phát triển bền vững thường niên 2025, tổng kết các hoạt động về môi trường, xã hội và quản trị (ESG).', 'Báo cáo nêu bật những nỗ lực giảm phát thải trong quá trình thi công cũng như các sáng kiến tiết kiệm năng lượng đang áp dụng tại dự án.', 'Đây là năm thứ ba liên tiếp Terra thực hiện báo cáo minh bạch này, thể hiện cam kết phát triển lâu dài cùng cộng đồng.']::text[], '2026-02-10', false, true),
  (9, 'thien-nguyen', 'Trao 200 suất học bổng "Ước mơ xanh" cho học sinh vùng ven sông', array['Chương trình "Ước mơ xanh" đã trao 200 suất học bổng cho các em học sinh có hoàn cảnh khó khăn tại khu vực ven sông gần dự án.', 'Bên cạnh học bổng, chương trình còn tặng dụng cụ học tập và tổ chức các buổi sinh hoạt ngoại khoá cho các em.', 'Đây là hoạt động thường niên nằm trong chiến lược trách nhiệm xã hội mà Terra duy trì trong nhiều năm qua.', 'Mỗi suất học bổng trị giá 3 triệu đồng, được trao trực tiếp cho học sinh và gia đình tại buổi lễ tổ chức ở 5 điểm trường thuộc khu vực ven sông gần dự án.', 'Ngoài học bổng bằng tiền mặt, chương trình còn tặng kèm 200 bộ sách giáo khoa mới cùng balo, dụng cụ học tập cho năm học tới.', 'Nhiều giáo viên tại các điểm trường cho biết chương trình đã giúp giảm đáng kể tỷ lệ học sinh bỏ học giữa chừng vì khó khăn kinh tế trong hai năm gần đây.', 'Terra cho biết sẽ mở rộng quy mô học bổng lên 300 suất trong năm tới, đồng thời xem xét bổ sung hợp phần hỗ trợ học phí dài hạn cho các em có thành tích học tập xuất sắc.']::text[], '2026-06-01', true, true),
  (10, 'thien-nguyen', 'Chương trình "Mái ấm cho em" khởi công 10 căn nhà tình thương', array['Chương trình "Mái ấm cho em" chính thức khởi công xây dựng 10 căn nhà tình thương cho các hộ gia đình khó khăn trong khu vực.', 'Toàn bộ chi phí xây dựng được tài trợ bởi Terra, với sự tham gia thi công của chính đội ngũ kỹ sư và công nhân dự án.', 'Dự kiến các căn nhà sẽ hoàn thành và bàn giao trước dịp cuối năm, mang lại nơi ở an toàn cho các gia đình thụ hưởng.']::text[], '2026-04-20', true, true),
  (11, 'thien-nguyen', 'Cùng cư dân dọn rác, "Xanh hoá dòng sông" mùa đầu tiên', array['Mùa đầu tiên của chương trình "Xanh hoá dòng sông" thu hút đông đảo cư dân và tình nguyện viên tham gia dọn dẹp rác thải ven bờ sông.', 'Hoạt động không chỉ góp phần cải thiện cảnh quan môi trường mà còn nâng cao ý thức bảo vệ dòng sông trong cộng đồng dân cư.', 'Terra cam kết duy trì chương trình định kỳ hàng quý, hướng tới một không gian sống xanh và bền vững.']::text[], '2026-01-15', false, true),
  (12, 'du-an', 'Terra mở bán đợt 2: hơn 500 căn hộ view sông chính thức ra mắt', array['Đợt mở bán thứ 2 của Terra giới thiệu hơn 500 căn hộ view sông trực diện, tập trung tại 2 tòa tháp cao nhất dự án.', 'Giỏ hàng lần này được đánh giá có vị trí đẹp và pháp lý minh bạch, thu hút lượng lớn khách hàng đăng ký giữ chỗ ngay trong ngày đầu.', 'Chủ đầu tư cho biết mức giá vẫn được giữ ổn định so với đợt 1 nhằm tri ân khách hàng đã đồng hành từ sớm.']::text[], '2025-11-05', false, true),
  (13, 'du-an', 'Ngân hàng ABC chính thức bảo lãnh tiến độ cho dự án Terra', array['Terra vừa công bố hợp tác bảo lãnh tiến độ bàn giao với một ngân hàng thương mại uy tín, tăng thêm sự an tâm cho khách hàng mua nhà.', 'Theo thỏa thuận, khách hàng sẽ được hoàn tiền nếu chủ đầu tư chậm bàn giao so với cam kết trong hợp đồng.', 'Đây là bước đi nhằm minh bạch hóa quá trình phát triển dự án, phù hợp với quy định pháp luật kinh doanh bất động sản hiện hành.']::text[], '2025-10-18', false, true),
  (14, 'du-an', 'Cận cảnh tiện ích hồ bơi vô cực tầng mái Terra trước ngày khánh thành', array['Hồ bơi vô cực tại tầng mái Terra đã hoàn thiện phần thi công, mang đến tầm nhìn toàn cảnh sông nước cho cư dân.', 'Khu vực này được tích hợp cùng quầy bar mini, khu thư giãn ngoài trời và hệ thống chiếu sáng cảnh quan về đêm.', 'Tiện ích dự kiến chính thức đưa vào vận hành ngay khi giai đoạn bàn giao căn hộ hoàn tất.']::text[], '2025-09-22', false, true),
  (15, 'du-an', 'Terra công bố chính sách thanh toán giãn tiến độ 36 tháng', array['Nhằm hỗ trợ khách hàng tối ưu dòng tiền, Terra triển khai chính sách thanh toán giãn tiến độ kéo dài đến 36 tháng.', 'Khách hàng chỉ cần thanh toán 30% giá trị căn hộ để ký hợp đồng mua bán, phần còn lại chia đều theo tiến độ xây dựng.', 'Chính sách áp dụng cho tất cả các loại hình sản phẩm đang mở bán tại dự án.']::text[], '2025-08-30', false, true),
  (16, 'du-an', 'Khởi công giai đoạn 2: bổ sung 3 tòa tháp cao 45 tầng', array['Terra chính thức khởi công giai đoạn 2 với quy mô 3 tòa tháp cao 45 tầng, nâng tổng số căn hộ toàn dự án lên hơn 4.000 căn.', 'Giai đoạn mới được quy hoạch đồng bộ cùng hệ thống tiện ích nội khu, kết nối liền mạch với giai đoạn 1 đã đi vào vận hành.', 'Chủ đầu tư kỳ vọng hoàn thiện phần thô trong vòng 18 tháng, bàn giao đúng tiến độ như các giai đoạn trước.', 'Tổng vốn đầu tư cho giai đoạn 2 ước tính khoảng 8.500 tỷ đồng, tập trung vào ba tòa tháp căn hộ cao cấp và một khối đế thương mại tích hợp trung tâm thương mại quy mô nhỏ.', 'Đơn vị thi công chính tiếp tục là tổng thầu đã đảm nhiệm giai đoạn 1, đảm bảo tính đồng bộ về chất lượng thi công và tiến độ giữa các giai đoạn.', 'Dự kiến phần móng và tầng hầm sẽ hoàn thành trong quý II/2027, làm tiền đề để triển khai đồng loạt phần thân vào cuối năm.', 'Chủ đầu tư cũng công bố chính sách giá ưu đãi đặc biệt cho 100 khách hàng đăng ký sớm nhất trong đợt mở bán giai đoạn 2, dự kiến diễn ra ngay sau lễ khởi công.']::text[], '2025-07-14', false, true),
  (17, 'du-an', 'Terra hoàn thiện hạ tầng cảnh quan công viên trung tâm rộng 2ha', array['Công viên trung tâm rộng 2ha của Terra đã hoàn thiện phần cảnh quan, cây xanh và hệ thống đường dạo bộ.', 'Khu vực này được thiết kế với nhiều phân khu chức năng: sân chơi trẻ em, đường chạy bộ và khu tập thể dục ngoài trời.', 'Đây là một trong những tiện ích được cư dân mong chờ nhất kể từ khi dự án khởi công.']::text[], '2025-06-02', false, true),
  (18, 'du-an', 'Cất nóc tòa tháp đầu tiên sau 14 tháng thi công', array['Sau 14 tháng thi công liên tục, tòa tháp đầu tiên của Terra đã chính thức cất nóc, vượt tiến độ đề ra ban đầu.', 'Buổi lễ có sự tham gia của đại diện chủ đầu tư, đơn vị thi công và đông đảo khách hàng đã ký hợp đồng mua căn hộ.', 'Đây là cột mốc quan trọng, đánh dấu dự án bước sang giai đoạn hoàn thiện và lắp đặt nội thất.']::text[], '2025-04-25', false, true),
  (19, 'cong-ty', 'Terra lọt Top 10 chủ đầu tư uy tín năm 2026', array['Terra được vinh danh trong Top 10 chủ đầu tư bất động sản uy tín năm 2026 do một tổ chức nghiên cứu thị trường độc lập bình chọn.', 'Kết quả dựa trên khảo sát năng lực tài chính, tiến độ triển khai dự án và mức độ hài lòng của khách hàng.', 'Đây là năm thứ hai liên tiếp Terra góp mặt trong bảng xếp hạng này.']::text[], '2025-12-20', false, true),
  (20, 'cong-ty', 'Ra mắt bộ nhận diện thương hiệu mới của Terra', array['Terra chính thức ra mắt bộ nhận diện thương hiệu mới, đồng bộ từ logo, màu sắc đến hệ thống ấn phẩm truyền thông.', 'Bộ nhận diện mới hướng tới hình ảnh hiện đại, gần gũi hơn với thế hệ khách hàng trẻ đang tìm kiếm không gian sống chất lượng.', 'Thay đổi này nằm trong chiến lược tái định vị thương hiệu dài hạn của công ty.']::text[], '2025-11-11', false, true),
  (21, 'cong-ty', 'Terra khai trương văn phòng giao dịch thứ 5 tại trung tâm thành phố', array['Văn phòng giao dịch thứ 5 của Terra vừa khai trương tại khu vực trung tâm thành phố, mở rộng mạng lưới tư vấn và chăm sóc khách hàng.', 'Không gian văn phòng được thiết kế theo mô hình trải nghiệm, tích hợp phòng chiếu 3D và khu vực trưng bày căn hộ mẫu thu nhỏ.', 'Đây là một phần trong kế hoạch mở rộng hiện diện thương hiệu tại các đô thị lớn.']::text[], '2025-10-05', false, true),
  (22, 'cong-ty', 'Lễ ký kết hợp tác phân phối độc quyền cùng đại lý XYZ Land', array['Terra và đại lý XYZ Land vừa ký kết thỏa thuận hợp tác phân phối độc quyền cho các sản phẩm thuộc giai đoạn 2 của dự án.', 'Sự hợp tác này giúp mở rộng kênh tiếp cận khách hàng tại nhiều tỉnh thành trên cả nước.', 'Hai bên cam kết đồng hành lâu dài, đảm bảo chất lượng tư vấn và dịch vụ hậu mãi cho khách hàng.']::text[], '2025-09-08', false, true),
  (23, 'cong-ty', 'Terra tổ chức hội nghị nhà đầu tư thường niên 2025', array['Hội nghị nhà đầu tư thường niên 2025 của Terra thu hút hơn 300 nhà đầu tư và đối tác tham dự.', 'Tại sự kiện, ban lãnh đạo công ty đã cập nhật kết quả kinh doanh, tiến độ các dự án và định hướng phát triển trong giai đoạn tới.', 'Nhiều câu hỏi từ nhà đầu tư về chiến lược mở rộng quỹ đất cũng được giải đáp trực tiếp tại sự kiện.']::text[], '2025-07-19', false, true),
  (24, 'cong-ty', 'Bổ nhiệm Tổng giám đốc mới, định hướng phát triển giai đoạn 2026-2030', array['Terra công bố quyết định bổ nhiệm Tổng giám đốc mới, người có hơn 15 năm kinh nghiệm trong lĩnh vực bất động sản.', 'Dưới sự dẫn dắt mới, công ty đặt mục tiêu mở rộng quỹ dự án và nâng cao chất lượng sản phẩm trong giai đoạn 2026-2030.', 'Ban lãnh đạo khẳng định các cam kết với khách hàng và đối tác hiện tại vẫn được giữ nguyên và tiếp tục thực hiện đầy đủ.', 'Tân Tổng giám đốc từng đảm nhiệm vị trí quản lý cấp cao tại một số tập đoàn bất động sản lớn trong và ngoài nước, với thế mạnh về phát triển quỹ đất và vận hành dự án quy mô lớn.', 'Trong buổi lễ công bố, tân Tổng giám đốc chia sẻ ba định hướng ưu tiên: đẩy nhanh tiến độ bàn giao đúng cam kết, mở rộng quỹ dự án tại các đô thị vệ tinh, và số hóa toàn diện quy trình chăm sóc khách hàng.', 'Hội đồng quản trị Terra khẳng định việc thay đổi nhân sự cấp cao nằm trong lộ trình tái cấu trúc đã được lên kế hoạch từ cuối năm 2025, không ảnh hưởng đến hoạt động vận hành thường nhật của công ty.']::text[], '2025-05-30', false, true),
  (25, 'cong-ty', 'Terra đạt chứng nhận công trình xanh EDGE', array['Terra chính thức đạt chứng nhận công trình xanh EDGE, ghi nhận nỗ lực tiết kiệm năng lượng, nước và vật liệu xây dựng.', 'Chứng nhận được đánh giá bởi tổ chức quốc tế độc lập dựa trên các tiêu chí thiết kế và vận hành bền vững.', 'Đây là bước đi quan trọng trong chiến lược phát triển các dự án theo tiêu chuẩn xanh của công ty.']::text[], '2025-03-12', false, true),
  (26, 'thien-nguyen', 'Chương trình "Tết ấm cho người nghèo" trao 500 phần quà Tết', array['Nhân dịp Tết Nguyên đán, Terra phối hợp cùng chính quyền địa phương trao 500 phần quà cho các hộ gia đình có hoàn cảnh khó khăn.', 'Mỗi phần quà gồm nhu yếu phẩm và một khoản tiền mặt nhỏ, giúp các gia đình đón một cái Tết ấm áp và đủ đầy hơn.', 'Chương trình được duy trì hàng năm như một hoạt động ý nghĩa gắn kết cộng đồng xung quanh dự án.']::text[], '2026-01-28', false, true),
  (27, 'thien-nguyen', 'Terra tài trợ xây dựng thư viện cộng đồng cho 3 trường tiểu học', array['Terra tài trợ kinh phí xây dựng và trang bị sách vở cho thư viện tại 3 trường tiểu học trong khu vực lân cận dự án.', 'Mỗi thư viện được trang bị hơn 1.000 đầu sách cùng khu vực đọc sách sáng tạo dành cho học sinh.', 'Hoạt động nằm trong chuỗi chương trình khuyến khích văn hóa đọc mà Terra hướng tới trong dài hạn.']::text[], '2025-11-16', false, true),
  (28, 'thien-nguyen', 'Ngày hội hiến máu nhân đạo thu hút hơn 300 người tham gia', array['Ngày hội hiến máu nhân đạo do Terra phối hợp tổ chức đã thu hút hơn 300 cán bộ nhân viên và cư dân tham gia.', 'Toàn bộ lượng máu thu được sẽ được chuyển tới các bệnh viện trong khu vực, góp phần bổ sung nguồn máu dự trữ đang thiếu hụt.', 'Đây là hoạt động thường niên nhận được sự hưởng ứng tích cực từ cộng đồng cư dân Terra.']::text[], '2025-10-09', false, true),
  (29, 'thien-nguyen', 'Chiến dịch trồng 1.000 cây xanh dọc bờ sông hưởng ứng Ngày Môi trường', array['Hưởng ứng Ngày Môi trường thế giới, Terra phát động chiến dịch trồng 1.000 cây xanh dọc tuyến bờ sông gần dự án.', 'Hoạt động thu hút sự tham gia của cán bộ nhân viên, cư dân và các tình nguyện viên trong khu vực.', 'Chiến dịch góp phần cải thiện cảnh quan, chống xói mòn bờ sông và nâng cao ý thức bảo vệ môi trường.']::text[], '2025-08-05', false, true),
  (30, 'thien-nguyen', 'Hỗ trợ khẩn cấp đồng bào vùng lũ miền Trung', array['Trước tình hình mưa lũ nghiêm trọng tại miền Trung, Terra đã nhanh chóng huy động và gửi tặng nhu yếu phẩm thiết yếu tới các hộ dân bị ảnh hưởng.', 'Đoàn thiện nguyện của công ty đã trực tiếp có mặt tại vùng lũ để trao quà và hỗ trợ khắc phục hậu quả cùng người dân.', 'Terra cam kết tiếp tục đồng hành, hỗ trợ dài hạn cho công tác tái thiết sau thiên tai.']::text[], '2025-07-01', false, true),
  (31, 'thien-nguyen', 'Chương trình "Bữa cơm yêu thương" cho bệnh nhân nghèo tại bệnh viện tỉnh', array['Chương trình "Bữa cơm yêu thương" của Terra cung cấp hàng trăm suất cơm miễn phí mỗi tuần cho bệnh nhân nghèo tại bệnh viện tỉnh.', 'Các suất ăn được chuẩn bị đảm bảo dinh dưỡng và an toàn vệ sinh thực phẩm, do đội ngũ tình nguyện viên trực tiếp phân phát.', 'Chương trình dự kiến sẽ được nhân rộng ra thêm nhiều cơ sở y tế khác trong thời gian tới.']::text[], '2025-05-20', false, true),
  (32, 'thien-nguyen', 'Terra đồng hành cùng giải chạy thiện nguyện "Vì trẻ em vùng cao"', array['Terra là nhà tài trợ đồng hành cùng giải chạy thiện nguyện "Vì trẻ em vùng cao", quy tụ hàng nghìn người tham gia.', 'Toàn bộ kinh phí gây quỹ từ giải chạy được sử dụng để xây dựng điểm trường và hỗ trợ dinh dưỡng cho trẻ em vùng cao.', 'Sự kiện góp phần lan tỏa tinh thần thể thao gắn liền với trách nhiệm xã hội trong cộng đồng.']::text[], '2025-03-08', false, true),
  (33, 'du-an', 'Terra hoàn thiện thang máy tốc độ cao cho toàn bộ các tòa tháp', array['Hệ thống thang máy tốc độ cao đã được lắp đặt hoàn chỉnh cho toàn bộ các tòa tháp tại Terra, rút ngắn đáng kể thời gian di chuyển của cư dân.', 'Công nghệ thang máy thông minh cho phép gọi trước tầng qua ứng dụng di động, hạn chế tối đa thời gian chờ vào giờ cao điểm.', 'Đây là một trong những hạng mục kỹ thuật cuối cùng trước khi bàn giao toàn bộ tiện ích nội khu.']::text[], '2025-12-05', false, true),
  (34, 'du-an', 'Ra mắt nhà mẫu 3 phòng ngủ view sông tại Terra', array['Căn hộ mẫu 3 phòng ngủ view sông chính thức mở cửa đón khách tham quan, mang đến trải nghiệm thực tế về không gian sống tại Terra.', 'Nội thất được bài trí theo phong cách hiện đại, tối ưu ánh sáng tự nhiên và tận dụng tối đa tầm nhìn hướng sông.', 'Khách hàng có thể đặt lịch tham quan trực tiếp tại văn phòng bán hàng của dự án.']::text[], '2025-11-22', false, true),
  (35, 'du-an', 'Terra lắp đặt hệ thống pin năng lượng mặt trời cho khu tiện ích', array['Khu tiện ích nội khu của Terra được trang bị hệ thống pin năng lượng mặt trời, giảm tải chi phí vận hành chiếu sáng công cộng.', 'Đây là một phần trong định hướng phát triển dự án theo tiêu chuẩn công trình xanh mà chủ đầu tư đang theo đuổi.', 'Hệ thống dự kiến đáp ứng khoảng 30% nhu cầu điện năng cho khu vực tiện ích chung.']::text[], '2025-10-30', false, true),
  (36, 'du-an', 'Cập nhật tiến độ tháng 9: hoàn thiện 80% phần thô toàn dự án', array['Tính đến hết tháng 9, Terra đã hoàn thiện khoảng 80% khối lượng phần thô trên toàn dự án, đúng theo kế hoạch đã công bố.', 'Các hạng mục cơ điện, hoàn thiện mặt ngoài đang được triển khai song song để đảm bảo tiến độ bàn giao.', 'Chủ đầu tư cam kết tiếp tục cập nhật tiến độ minh bạch tới khách hàng theo từng quý.']::text[], '2025-09-14', false, true),
  (37, 'du-an', 'Terra công bố lộ trình bàn giao chi tiết giai đoạn 2', array['Lộ trình bàn giao chi tiết cho giai đoạn 2 của Terra vừa được công bố, chia thành 3 đợt bàn giao theo từng cụm tòa tháp.', 'Khách hàng có thể tra cứu thời gian bàn giao dự kiến cho từng căn hộ ngay trên ứng dụng chăm sóc khách hàng.', 'Việc công bố lộ trình chi tiết nhằm giúp cư dân chủ động sắp xếp kế hoạch chuyển về sinh sống.']::text[], '2025-08-18', false, true),
  (38, 'du-an', 'Sảnh đón khách 5 sao chính thức đưa vào vận hành', array['Sảnh đón khách theo tiêu chuẩn 5 sao tại khối đế Terra đã chính thức đưa vào vận hành, phục vụ cư dân và khách tham quan.', 'Không gian sảnh được thiết kế sang trọng với quầy lễ tân riêng, khu vực chờ và hệ thống an ninh kiểm soát ra vào hiện đại.', 'Đây là điểm nhấn quan trọng góp phần nâng tầm trải nghiệm sống tại dự án.']::text[], '2025-07-25', false, true),
  (39, 'du-an', 'Terra mở rộng bãi đỗ xe ngầm thêm 200 chỗ', array['Trước nhu cầu gửi xe ngày càng tăng, Terra quyết định mở rộng bãi đỗ xe ngầm thêm 200 chỗ, nâng tổng công suất toàn khu.', 'Khu vực mở rộng được trang bị hệ thống thông gió và camera giám sát 24/7, đảm bảo an toàn cho phương tiện của cư dân.', 'Hạng mục dự kiến hoàn thành trước đợt bàn giao tiếp theo.']::text[], '2025-06-20', false, true),
  (40, 'du-an', 'Chính thức thông xe tuyến đường nội khu kết nối cổng chính', array['Tuyến đường nội khu kết nối trực tiếp với cổng chính của Terra đã chính thức thông xe, rút ngắn thời gian di chuyển ra vào dự án.', 'Tuyến đường được thiết kế 2 làn xe, có vỉa hè và hệ thống cây xanh hai bên, đồng bộ với cảnh quan chung.', 'Việc thông xe giúp giảm tải cho các lối đi tạm trong quá trình thi công trước đó.']::text[], '2025-05-15', false, true),
  (41, 'cong-ty', 'Terra tăng vốn điều lệ, mở rộng quy mô đầu tư', array['Terra vừa hoàn tất tăng vốn điều lệ nhằm chuẩn bị nguồn lực cho các dự án mới trong kế hoạch phát triển trung hạn.', 'Nguồn vốn bổ sung sẽ ưu tiên cho việc mở rộng quỹ đất và nâng cấp chất lượng thi công tại các dự án hiện hữu.', 'Đây là bước đi thể hiện cam kết phát triển dài hạn của công ty trong lĩnh vực bất động sản.']::text[], '2025-12-18', false, true),
  (42, 'cong-ty', 'Ký kết hợp tác cùng đơn vị quản lý vận hành quốc tế', array['Terra vừa ký kết hợp tác chiến lược với một đơn vị quản lý vận hành bất động sản quốc tế nhằm nâng cao chất lượng dịch vụ.', 'Đơn vị đối tác sẽ trực tiếp tham gia vận hành các tiện ích nội khu, đảm bảo trải nghiệm sống theo chuẩn quốc tế cho cư dân.', 'Hợp tác này là bước chuẩn bị quan trọng trước thềm bàn giao giai đoạn 2.']::text[], '2025-11-27', false, true),
  (43, 'cong-ty', 'Terra ra mắt ứng dụng chăm sóc khách hàng trên di động', array['Ứng dụng di động mới của Terra cho phép khách hàng tra cứu tiến độ, hồ sơ thanh toán và đặt lịch tham quan chỉ trong vài thao tác.', 'Ứng dụng cũng tích hợp kênh hỗ trợ trực tuyến 24/7, giúp giải đáp nhanh chóng mọi thắc mắc của khách hàng.', 'Đây là một phần trong chiến lược chuyển đổi số toàn diện mà Terra đang triển khai.']::text[], '2025-10-21', false, true),
  (44, 'cong-ty', 'Đón đoàn famtrip đối tác quốc tế tham quan dự án', array['Terra vừa đón đoàn famtrip gồm các đối tác, nhà đầu tư quốc tế đến tham quan thực tế tiến độ và tiện ích dự án.', 'Đoàn tham quan đánh giá cao chất lượng thi công cũng như vị trí chiến lược của Terra trong khu vực.', 'Chuyến famtrip mở ra nhiều cơ hội hợp tác phát triển trong tương lai.']::text[], '2025-09-19', false, true),
  (45, 'cong-ty', 'Terra đạt mốc 5.000 khách hàng tin tưởng lựa chọn', array['Terra chính thức cán mốc 5.000 khách hàng lựa chọn an cư và đầu tư kể từ khi dự án mở bán.', 'Đây là cột mốc quan trọng, khẳng định niềm tin của thị trường dành cho thương hiệu Terra.', 'Chủ đầu tư tổ chức sự kiện tri ân đặc biệt dành cho các khách hàng đã đồng hành trong suốt thời gian qua.']::text[], '2025-08-12', false, true),
  (46, 'cong-ty', 'Thành lập quỹ hỗ trợ khởi nghiệp cộng đồng cư dân', array['Terra công bố thành lập quỹ hỗ trợ khởi nghiệp dành riêng cho cư dân trong dự án, khuyến khích các ý tưởng kinh doanh nhỏ tại khối đế thương mại.', 'Quỹ sẽ hỗ trợ một phần chi phí mặt bằng ban đầu cho các dự án khởi nghiệp được lựa chọn.', 'Đây là sáng kiến nhằm xây dựng một cộng đồng cư dân gắn kết và cùng phát triển.']::text[], '2025-07-08', false, true),
  (47, 'cong-ty', 'Terra mở văn phòng đại diện tại khu vực miền Bắc', array['Văn phòng đại diện mới tại khu vực miền Bắc chính thức đi vào hoạt động, mở rộng khả năng tiếp cận khách hàng của Terra.', 'Văn phòng cung cấp đầy đủ dịch vụ tư vấn, hỗ trợ thủ tục mua bán như tại trụ sở chính.', 'Đây là bước đi trong chiến lược phủ rộng thương hiệu trên phạm vi toàn quốc.']::text[], '2025-06-03', false, true),
  (48, 'cong-ty', 'Ra mắt kênh thông tin minh bạch tiến độ dự án trực tuyến', array['Terra ra mắt kênh thông tin trực tuyến cập nhật hình ảnh, video tiến độ thi công theo thời gian thực.', 'Khách hàng có thể theo dõi tiến độ dự án mọi lúc mọi nơi mà không cần đến trực tiếp công trường.', 'Kênh thông tin được xem là bước tiến trong nỗ lực minh bạch hóa thông tin của chủ đầu tư.']::text[], '2025-04-27', false, true),
  (49, 'cong-ty', 'Terra hợp tác cùng ngân hàng triển khai gói vay ưu đãi mới', array['Gói vay ưu đãi mới được triển khai với lãi suất cạnh tranh, hỗ trợ khách hàng dễ dàng tiếp cận nguồn vốn mua nhà.', 'Thời gian vay có thể kéo dài lên đến 30 năm, giảm áp lực tài chính hàng tháng cho người mua.', 'Đây là một trong nhiều chương trình hợp tác tài chính mà Terra liên tục mở rộng cùng các ngân hàng đối tác.']::text[], '2025-03-21', false, true),
  (50, 'cong-ty', 'Vinh danh đội ngũ nhân viên xuất sắc năm 2025', array['Terra tổ chức lễ vinh danh, tri ân những cá nhân và tập thể có đóng góp xuất sắc trong năm 2025.', 'Sự kiện là dịp để ban lãnh đạo ghi nhận nỗ lực của đội ngũ nhân viên trong suốt một năm nhiều thử thách.', 'Đây cũng là hoạt động thường niên nhằm lan tỏa tinh thần gắn kết trong nội bộ công ty.']::text[], '2025-01-16', false, true),
  (51, 'thien-nguyen', 'Chương trình khám bệnh miễn phí cho người cao tuổi trong khu vực', array['Terra phối hợp cùng đội ngũ y bác sĩ tổ chức khám bệnh, cấp phát thuốc miễn phí cho hơn 200 người cao tuổi trong khu vực.', 'Chương trình bao gồm khám tổng quát, đo huyết áp, tư vấn dinh dưỡng phù hợp với người lớn tuổi.', 'Đây là hoạt động chăm sóc sức khỏe cộng đồng được Terra duy trì định kỳ mỗi năm.']::text[], '2025-12-27', false, true),
  (52, 'thien-nguyen', 'Trao tặng xe đạp đến trường cho học sinh khó khăn', array['Terra trao tặng 100 chiếc xe đạp cho học sinh có hoàn cảnh khó khăn, giúp các em thuận tiện hơn trên hành trình đến trường.', 'Hoạt động được thực hiện tại các trường tiểu học và trung học cơ sở trong khu vực lân cận dự án.', 'Nhiều phụ huynh và thầy cô bày tỏ sự xúc động trước tấm lòng của chương trình.']::text[], '2025-11-14', false, true),
  (53, 'thien-nguyen', 'Terra tổ chức Trung thu yêu thương cho thiếu nhi', array['Đêm hội Trung thu yêu thương do Terra tổ chức mang đến niềm vui cho hàng trăm thiếu nhi trong khu vực với lồng đèn, bánh kẹo và các trò chơi dân gian.', 'Chương trình còn có phần trao quà cho các em nhỏ có hoàn cảnh đặc biệt khó khăn.', 'Đây là hoạt động thường niên được trẻ em trong khu vực mong chờ mỗi dịp Trung thu.']::text[], '2025-09-27', false, true),
  (54, 'thien-nguyen', 'Chung tay xây dựng sân chơi cộng đồng cho trẻ em ven sông', array['Terra cùng các tình nguyện viên hoàn thành một sân chơi cộng đồng dành cho trẻ em tại khu vực ven sông gần dự án.', 'Sân chơi được trang bị các thiết bị vận động an toàn, tạo không gian sinh hoạt lành mạnh cho trẻ nhỏ sau giờ học.', 'Công trình là món quà ý nghĩa gửi tới cộng đồng dân cư xung quanh dự án.']::text[], '2025-08-23', false, true),
  (55, 'thien-nguyen', 'Chương trình "Áo ấm mùa đông" hỗ trợ hộ nghèo', array['Chương trình "Áo ấm mùa đông" trao tặng hàng trăm bộ quần áo ấm cho các hộ gia đình nghèo trước thềm mùa lạnh.', 'Toàn bộ quần áo được quyên góp từ cán bộ nhân viên Terra và cư dân trong dự án.', 'Hoạt động thể hiện tinh thần sẻ chia, tương thân tương ái trong cộng đồng.']::text[], '2025-07-11', false, true),
  (56, 'thien-nguyen', 'Terra tài trợ thiết bị y tế cho trạm xá địa phương', array['Terra tài trợ một số thiết bị y tế cơ bản cho trạm xá địa phương, góp phần nâng cao chất lượng khám chữa bệnh ban đầu cho người dân.', 'Thiết bị được bàn giao trực tiếp cùng đại diện chính quyền và cán bộ y tế địa phương.', 'Đây là hoạt động nằm trong chuỗi chương trình chăm sóc sức khỏe cộng đồng của Terra.']::text[], '2025-06-09', false, true),
  (57, 'thien-nguyen', 'Ngày hội đổi rác lấy quà, lan tỏa lối sống xanh', array['Ngày hội "Đổi rác lấy quà" thu hút đông đảo cư dân tham gia phân loại và mang rác tái chế đến đổi lấy những phần quà xanh.', 'Hoạt động nhằm nâng cao ý thức phân loại rác thải và khuyến khích lối sống thân thiện với môi trường.', 'Terra dự kiến tổ chức sự kiện này định kỳ hàng quý trong khu vực nội khu.']::text[], '2025-05-04', false, true),
  (58, 'thien-nguyen', 'Hỗ trợ sinh kế cho các hộ dân bị ảnh hưởng bởi thi công', array['Terra triển khai chương trình hỗ trợ sinh kế cho các hộ dân bị ảnh hưởng trong quá trình thi công dự án.', 'Hỗ trợ bao gồm đào tạo nghề ngắn hạn và kết nối việc làm tại các đơn vị đối tác của dự án.', 'Chương trình thể hiện trách nhiệm của chủ đầu tư đối với cộng đồng dân cư xung quanh.']::text[], '2025-03-30', false, true),
  (59, 'thien-nguyen', 'Terra đồng hành cùng chương trình tiêm chủng miễn phí', array['Terra phối hợp cùng trung tâm y tế địa phương tổ chức tiêm chủng miễn phí cho trẻ em trong khu vực dự án.', 'Chương trình góp phần đảm bảo tỷ lệ tiêm chủng đầy đủ, phòng ngừa các bệnh truyền nhiễm nguy hiểm cho trẻ nhỏ.', 'Đây là hoạt động phối hợp thường niên giữa Terra và ngành y tế địa phương.']::text[], '2025-02-14', false, true),
  (60, 'thien-nguyen', 'Lễ trao nhà tình nghĩa cho gia đình chính sách', array['Terra trao tặng một căn nhà tình nghĩa cho gia đình chính sách có hoàn cảnh khó khăn tại địa phương.', 'Căn nhà được xây dựng kiên cố, đầy đủ tiện nghi cơ bản, giúp gia đình ổn định cuộc sống lâu dài.', 'Đây là hoạt động tri ân ý nghĩa mà Terra thực hiện nhân dịp đầu năm mới.']::text[], '2025-01-20', false, true)
on conflict (id) do update set
  category = excluded.category,
  title = excluded.title,
  content = excluded.content,
  published_at = excluded.published_at,
  is_featured = excluded.is_featured,
  is_published = excluded.is_published;
select setval(pg_get_serial_sequence('public.news', 'id'), (select max(id) from public.news));

-- Tuyển dụng
insert into public.jobs (id, title, location, employment_type, summary, icon, is_open, sort_order) overriding system value
values
  (1, 'Chuyên viên Kinh doanh Bất động sản', 'TP.HCM', 'Toàn thời gian', 'Tư vấn, giới thiệu sản phẩm và chăm sóc khách hàng cho các dự án đang mở bán của Terra.', 'building', true, 0),
  (2, 'Trưởng phòng Marketing', 'TP.HCM', 'Toàn thời gian', 'Xây dựng chiến lược thương hiệu, truyền thông đa kênh cho danh mục dự án của công ty.', 'megaphone', true, 1),
  (3, 'Kỹ sư Giám sát công trình', 'Bình Dương', 'Toàn thời gian', 'Giám sát chất lượng, tiến độ thi công thực tế tại công trường theo đúng hồ sơ thiết kế.', 'engineer', true, 2),
  (4, 'Chuyên viên Chăm sóc khách hàng', 'TP.HCM', 'Toàn thời gian', 'Hỗ trợ, giải đáp và đồng hành cùng cư dân trong suốt quá trình sử dụng dịch vụ tại dự án.', 'support', true, 3),
  (5, 'Chuyên viên Pháp lý dự án', 'TP.HCM', 'Toàn thời gian', 'Soát xét hồ sơ pháp lý, hỗ trợ thủ tục cấp phép và sổ hồng cho các dự án đang triển khai.', 'legal', true, 4),
  (6, 'Kế toán tổng hợp', 'Đồng Nai', 'Toàn thời gian', 'Ghi nhận, đối soát chứng từ kế toán và lập báo cáo tài chính định kỳ cho khu vực phụ trách.', 'finance', true, 5)
on conflict (id) do update set
  title = excluded.title,
  location = excluded.location,
  employment_type = excluded.employment_type,
  summary = excluded.summary,
  icon = excluded.icon,
  is_open = excluded.is_open,
  sort_order = excluded.sort_order;
select setval(pg_get_serial_sequence('public.jobs', 'id'), (select max(id) from public.jobs));

-- Mặt bằng mặc định theo loại hình (thay toàn bộ mặt bằng con của bộ mặc định)
insert into public.floor_plan_sets (building_type, title, intro)
values ('apartment', 'Mặt bằng căn hộ', 'Các loại căn hộ được thiết kế tối ưu công năng, không gian sinh hoạt chung liền mạch, mọi phòng ngủ đều đón ánh sáng và gió tự nhiên.')
on conflict (building_type) where project_id is null do update set title = excluded.title, intro = excluded.intro;
delete from public.floor_plans where set_id = (select id from public.floor_plan_sets where building_type = 'apartment' and project_id is null);
insert into public.floor_plans (set_id, slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order)
select (select id from public.floor_plan_sets where building_type = 'apartment' and project_id is null), v.slug, v.name, v.code, v.area::numeric, v.bedrooms::int, v.bathrooms::int, v.note,
  v.width::numeric, v.depth::numeric, v.rooms::jsonb, v.sort_order::int
from (values
  ('a1', '1 phòng ngủ', 'A1', 52, 1, 1, 'Căn hộ nhỏ gọn cho người trẻ độc thân hoặc vợ chồng mới cưới, phù hợp cho thuê.', 8, 6.5, '[{"label":"Bếp","kind":"kitchen","x":0,"y":0,"w":3,"h":2.5},{"label":"WC","kind":"wc","x":3,"y":0,"w":2,"h":2.5},{"label":"Phòng ngủ","kind":"bed","x":5,"y":0,"w":3,"h":4.5},{"label":"Phòng khách","kind":"living","x":0,"y":2.5,"w":5,"h":4},{"label":"Ban công","kind":"outdoor","x":5,"y":4.5,"w":3,"h":2}]'::jsonb, 0),
  ('b2', '2 phòng ngủ', 'B2', 75, 2, 2, 'Lựa chọn phổ biến nhất cho gia đình trẻ, phòng ngủ master có WC riêng.', 10, 7.5, '[{"label":"Bếp","kind":"kitchen","x":0,"y":0,"w":3,"h":3.5},{"label":"WC","kind":"wc","x":3,"y":0,"w":2,"h":3.5},{"label":"Phòng ngủ master","kind":"bed","x":5,"y":0,"w":5,"h":3.5},{"label":"Phòng khách","kind":"living","x":0,"y":3.5,"w":6,"h":4},{"label":"Phòng ngủ 2","kind":"bed","x":6,"y":3.5,"w":4,"h":3},{"label":"Ban công","kind":"outdoor","x":6,"y":6.5,"w":4,"h":1}]'::jsonb, 1),
  ('c3', '3 phòng ngủ', 'C3', 96, 3, 2, 'Căn góc 2 mặt thoáng cho gia đình nhiều thế hệ, lô gia rộng để giặt phơi.', 12, 8, '[{"label":"Phòng ngủ 2","kind":"bed","x":0,"y":0,"w":3.5,"h":3.5},{"label":"WC","kind":"wc","x":3.5,"y":0,"w":2,"h":3.5},{"label":"Bếp","kind":"kitchen","x":5.5,"y":0,"w":3,"h":3.5},{"label":"Phòng ngủ 3","kind":"bed","x":8.5,"y":0,"w":3.5,"h":3.5},{"label":"Phòng khách","kind":"living","x":0,"y":3.5,"w":6.5,"h":4.5},{"label":"Phòng ngủ master","kind":"bed","x":6.5,"y":3.5,"w":4,"h":4.5},{"label":"WC","kind":"wc","x":10.5,"y":3.5,"w":1.5,"h":2.5},{"label":"Lô gia","kind":"outdoor","x":10.5,"y":6,"w":1.5,"h":2}]'::jsonb, 2)
) as v (slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order);

insert into public.floor_plan_sets (building_type, title, intro)
values ('villa', 'Mặt bằng biệt thự', 'Biệt thự song lập trên lô đất 12 × 15m, tầng 1 dành cho sinh hoạt chung và tiếp khách, tầng 2 là không gian nghỉ ngơi riêng tư của gia đình.')
on conflict (building_type) where project_id is null do update set title = excluded.title, intro = excluded.intro;
delete from public.floor_plans where set_id = (select id from public.floor_plan_sets where building_type = 'villa' and project_id is null);
insert into public.floor_plans (set_id, slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order)
select (select id from public.floor_plan_sets where building_type = 'villa' and project_id is null), v.slug, v.name, v.code, v.area::numeric, v.bedrooms::int, v.bathrooms::int, v.note,
  v.width::numeric, v.depth::numeric, v.rooms::jsonb, v.sort_order::int
from (values
  ('t1', 'Tầng 1', 'T1', 180, 1, 1, 'Gara ô tô, phòng khách thông tầng, bếp mở ra sân vườn phía sau.', 12, 15, '[{"label":"Gara","kind":"garage","x":0,"y":0,"w":4,"h":6},{"label":"Phòng khách","kind":"living","x":4,"y":0,"w":8,"h":7},{"label":"Phòng ngủ khách","kind":"bed","x":0,"y":6,"w":4,"h":5},{"label":"Bếp & ăn","kind":"kitchen","x":4,"y":7,"w":8,"h":5},{"label":"WC","kind":"wc","x":0,"y":11,"w":4,"h":2},{"label":"Kho","kind":"storage","x":0,"y":13,"w":4,"h":2},{"label":"Sân vườn","kind":"outdoor","x":4,"y":12,"w":8,"h":3}]'::jsonb, 0),
  ('t2', 'Tầng 2', 'T2', 180, 3, 2, 'Phòng ngủ master kèm phòng thay đồ và WC riêng, sảnh sinh hoạt chung cho gia đình.', 12, 15, '[{"label":"Phòng ngủ master","kind":"bed","x":0,"y":0,"w":7,"h":6},{"label":"WC master","kind":"wc","x":7,"y":0,"w":5,"h":3},{"label":"Phòng thay đồ","kind":"storage","x":7,"y":3,"w":5,"h":3},{"label":"Sảnh sinh hoạt","kind":"living","x":0,"y":6,"w":5,"h":5},{"label":"Phòng ngủ 2","kind":"bed","x":5,"y":6,"w":7,"h":5},{"label":"Phòng ngủ 3","kind":"bed","x":0,"y":11,"w":6,"h":4},{"label":"WC","kind":"wc","x":6,"y":11,"w":3,"h":4},{"label":"Ban công","kind":"outdoor","x":9,"y":11,"w":3,"h":4}]'::jsonb, 1)
) as v (slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order);

insert into public.floor_plan_sets (building_type, title, intro)
values ('land', 'Mặt bằng nhà phố gợi ý', 'Lô đất tiêu chuẩn 5 × 20m. Dưới đây là phương án thiết kế nhà phố 2 tầng gợi ý từ đội ngũ kiến trúc sư của Terra, giúp khách hàng hình dung công năng khi xây dựng.')
on conflict (building_type) where project_id is null do update set title = excluded.title, intro = excluded.intro;
delete from public.floor_plans where set_id = (select id from public.floor_plan_sets where building_type = 'land' and project_id is null);
insert into public.floor_plans (set_id, slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order)
select (select id from public.floor_plan_sets where building_type = 'land' and project_id is null), v.slug, v.name, v.code, v.area::numeric, v.bedrooms::int, v.bathrooms::int, v.note,
  v.width::numeric, v.depth::numeric, v.rooms::jsonb, v.sort_order::int
from (values
  ('l1', 'Tầng trệt', 'L1', 100, null, 1, 'Sân trước để xe, phòng khách rộng, giếng trời lấy sáng giữa nhà.', 5, 20, '[{"label":"Sân trước","kind":"outdoor","x":0,"y":0,"w":5,"h":3},{"label":"Phòng khách","kind":"living","x":0,"y":3,"w":5,"h":6},{"label":"Thang","kind":"stair","x":0,"y":9,"w":2,"h":3},{"label":"WC","kind":"wc","x":2,"y":9,"w":3,"h":2},{"label":"Giếng trời","kind":"outdoor","x":2,"y":11,"w":3,"h":1},{"label":"Bếp & ăn","kind":"kitchen","x":0,"y":12,"w":5,"h":6},{"label":"Sân sau","kind":"outdoor","x":0,"y":18,"w":5,"h":2}]'::jsonb, 0),
  ('l2', 'Tầng 1', 'L2', 100, 2, 1, 'Hai phòng ngủ trước – sau đều có cửa sổ lớn, sân phơi riêng phía sau.', 5, 20, '[{"label":"Ban công","kind":"outdoor","x":0,"y":0,"w":5,"h":2},{"label":"Phòng ngủ 1","kind":"bed","x":0,"y":2,"w":5,"h":6},{"label":"Thang","kind":"stair","x":0,"y":8,"w":2,"h":3},{"label":"WC","kind":"wc","x":2,"y":8,"w":3,"h":3},{"label":"Phòng ngủ 2","kind":"bed","x":0,"y":11,"w":5,"h":6},{"label":"Sân phơi","kind":"outdoor","x":0,"y":17,"w":5,"h":3}]'::jsonb, 1)
) as v (slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order);

insert into public.floor_plan_sets (building_type, title, intro)
values ('shophouse', 'Mặt bằng shophouse', 'Shophouse 6 × 18m: tầng trệt mặt tiền rộng tối ưu cho kinh doanh, các tầng trên bố trí khép kín để gia đình ở hoặc cho thuê văn phòng.')
on conflict (building_type) where project_id is null do update set title = excluded.title, intro = excluded.intro;
delete from public.floor_plans where set_id = (select id from public.floor_plan_sets where building_type = 'shophouse' and project_id is null);
insert into public.floor_plans (set_id, slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order)
select (select id from public.floor_plan_sets where building_type = 'shophouse' and project_id is null), v.slug, v.name, v.code, v.area::numeric, v.bedrooms::int, v.bathrooms::int, v.note,
  v.width::numeric, v.depth::numeric, v.rooms::jsonb, v.sort_order::int
from (values
  ('s1', 'Tầng trệt kinh doanh', 'S1', 108, null, 1, 'Không gian kinh doanh thông thoáng 60m², kho và bếp riêng phía sau.', 6, 18, '[{"label":"Khu kinh doanh","kind":"shop","x":0,"y":0,"w":6,"h":10},{"label":"Kho","kind":"storage","x":0,"y":10,"w":3,"h":2},{"label":"WC","kind":"wc","x":0,"y":12,"w":3,"h":2},{"label":"Thang","kind":"stair","x":3,"y":10,"w":3,"h":4},{"label":"Bếp","kind":"kitchen","x":0,"y":14,"w":6,"h":4}]'::jsonb, 0),
  ('s2', 'Tầng 2 – 3 ở', 'S2', 108, 2, 1, 'Phòng khách hướng ra mặt phố, hai phòng ngủ yên tĩnh phía sau.', 6, 18, '[{"label":"Phòng khách","kind":"living","x":0,"y":0,"w":6,"h":6},{"label":"Phòng ngủ 1","kind":"bed","x":0,"y":6,"w":6,"h":5},{"label":"WC","kind":"wc","x":0,"y":11,"w":3,"h":4},{"label":"Thang","kind":"stair","x":3,"y":11,"w":3,"h":4},{"label":"Phòng ngủ 2","kind":"bed","x":0,"y":15,"w":6,"h":3}]'::jsonb, 1)
) as v (slug, name, code, area, bedrooms, bathrooms, note, width, depth, rooms, sort_order);

commit;
